"""Identity of this build. Stdlib only — the hook imports nothing heavier.

Bump VERSION for every release. The update feed compares against it, and the
publish script refuses to upload a build whose VERSION does not match.
"""
VERSION = "0.2.0"

# Installed copies can never be changed after the fact, so this must be a URL
# we control forever. It is a thin proxy on the website; the backend behind it
# can move without stranding anyone.
UPDATE_URL = "https://vigilit.app/api/update"

# Ed25519 public key. Every update is verified against it before it installs.
# Generated by tools/release_keygen.py; the private half never leaves the
# publisher's machine. Changing this value orphans every existing install.
RELEASE_PUBLIC_KEY = "B8QQCqh+H4I/S6WGgzQrptQwAF/qjO6nTy5WDPI/Zck="
